backend:
  name: github
  repo: vitorregisrr/vitorr.dev
  branch: production
  site_domain: vitorr.netlify.com

locale: pt
publish_mode: editorial_workflow
media_folder: "static/assets/img"
public_folder: "/assets/img"

collections:
  - name: "posts"
    label: "Posts"
    folder: "data/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: 'YYYY-MM-DD hh:mm' }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Category", name: "category", widget: "select", options: ["js", "css", "html", "node", "misc"]}
      - { label: "Background", name: "background", widget: "select", options: [
          { label: "js", value: "#B31917" },
          { label: 'css', value: '#2DA0C3' },
          { label: 'html', value: '#D6BA32' },
          { label: 'node', value: '#637a91' },
          { label: 'misc', value: '#7AAB13' }
        ]}
      - { label: "Body", name: "body", widget: "markdown" }
